sudo: required
services:
  - docker

language: go

go:
  - 1.5.1

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    # - TARGETS="testsuite ES_HOST=elasticsearch-173"
    - TARGETS="-C libbeat testsuite ES_HOST=elasticsearch-210"
    - TARGETS="-C topbeat testsuite"
    - TARGETS="-C filebeat testsuite"
    - TARGETS="-C packetbeat testsuite"
    - TARGETS="-C libbeat crosscompile"
    - TARGETS="-C filebeat crosscompile"
  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

matrix:
  exclude:
    - os: osx
      env: TARGETS="check"
    - os: osx
      env: TARGETS="-C filebeat crosscompile"
    - os: osx
      env: TARGETS="-C libbeat crosscompile"
    - os: osx
      env: TARGETS="-C libbeat testsuite ES_HOST=elasticsearch-210"
  fast_finish: true
  allow_failures:
    - env: TARGETS="-C libbeat crosscompile"
    - env: TARGETS="-C filebeat crosscompile"


addons:
  apt:
    packages:
      - python-virtualenv
      - libpcap-dev
      - geoip-database

before_install:
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/elastic/beats/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/elastic/beats/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/elastic/beats/
  - cd $HOME/gopath/src/github.com/elastic/beats/
  # Docker-compose installation
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - true

script:
  - make $TARGETS

notifications:
  hipchat:
    rooms:
      secure: "iAQUMLIlghuQjGTvsNoiNU+Fok+IE0MYxhRjC9kwevXZgkY//w/Oa+w3Ol4kKDCQdSFOuPa72C73XOVznrL9Kw3y/gKU07Nf0WXMrq+TjPr/vR6gKGpDqeWe7WXJkhJS4tMjSs+bW0w+rQVo8QwYgsqeEQdDXgCzsfreytya/KA="

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
  - test -f filebeat/build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f filebeat/build/coverage/full.cov
  - test -f packetbeat/build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f packetbeat/build/coverage/full.cov
  - test -f topbeat/build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f topbeat/build/coverage/full.cov
  - test -f libbeat/build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f libbeat/build/coverage/full.cov
  - test -f winlogbeat/build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f winlogbeat/build/coverage/full.cov
