language: go

go:
  - 1.6

services:
  - docker

addons:
  apt:
    packages:
      - python-yaml
      - python-virtualenv

before_script:
  - wget https://github.com/Masterminds/glide/releases/download/0.10.1/glide-0.10.1-linux-386.tar.gz -O /tmp/glide.tar.gz
  - tar -xvf /tmp/glide.tar.gz
  - export PATH=$PATH:$PWD/linux-386/

script:
  - make test
